### ISSUE TITLE
Can not set

### ISSUE THREAD

**Issue by deaningithub** [pulipulichen/Python-Caller#1]
你好，看了你的文章所以來進行測試
安裝過程被防毒軟體偵測到為木馬病毒，不知哪一個階段存取到系統層級所以不被允許?
該如何設定比較正確還想請教你，謝謝!
Dean

**Comment by pulipulichen** [comment]
這是因為用了AutoIT產生exe檔案的關係，通常都會被防毒軟體認為是可疑軟體。

**Comment by deaningithub** [comment]
@pulipulichen 感謝!

**Comment by pulipulichen** [comment]
不客氣
